# HomepageX 后端配置

server:
  port: "8090"
  mode: debug # debug 或 release

# auths 认证配置
# 规则: user:pass@path1:perm,path2:perm2
auths:
  - admin:admin123@*:rw # 给 admin 分配所有路径的读写权限
  - user1:user123@/tools:rw,/*:ro # 给 user1 分配 /tools 路径的读写权限，其他路径只读
  - "@*,!/inner*" # 访客：所有路径可访问，无需认证，除了 /inner 开头的路径

# 图标缓存配置
# 页面使用: icons-local/{cdn-key}/{type:png|webp|svg}/{icon-name} 格式访问图标
# eg: icons-local/dashboard-icons/png/gitlab.png
icons_cdn:
  # 图标 CDN 配置：key 为本地使用前缀，value 为远程 CDN 基础路径
  # 本地：icons-local/{cdn-key}/png/gitlab.png
  # 远程：{IconsCDN[cdn-key]} + "png/gitlab.png"
  #
  # dashboard-icons 示例（来自 https://dashboardicons.com/）
  # 本地：icons-local/dashboard-icons/png/gitlab.png
  # 远程：https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/gitlab.png
  dashboard-icons: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/"

  # selfhst-icons 示例（来自 https://selfh.st/icons/）
  # 本地：icons-local/selfhst-icons/webp/openobserve.webp
  # 远程：https://cdn.jsdelivr.net/gh/selfhst/icons/webp/openobserve.webp
  selfhst-icons: "https://cdn.jsdelivr.net/gh/selfhst/icons/"

# 页面配置文件存放目录
pages_dir: "./pages"
# 前端构建目录
frontend_dir: "./frontend/build"

#
# 页面默认配置
# 所有页面都继承这些配置，可在页面配置文件中覆盖
page_defaults:
  theme: "ocean-depths"
# 默认导航配置
page_navs:
  - name: "Home"
    icon: "fas fa-home"
    url: "/"
  - name: "Tools"
    icon: "fas fa-tools"
    url: "/tools"
  - name: "InnerTools"
    icon: "fas fa-tools"
    url: "/inner-tools"
  - name: "Another"
    icon: "fas fa-star"
    url: "/another"
